### ISSUE TITLE
Allow the possibility to avoid the Setup Assistant

### ISSUE THREAD

**Issue by emanuelez** [gregneagle/pycreateuserpkg#11]
Right now, when the user first logs in, he's greeted by the Setup Assistant. Being able to automate that out of the way would be quite useful!

**Comment by gregneagle** [comment]
I do that with a separate package. There's tons of them on the internet.

You can even build one from scratch using munki-pkg and this recipe: https://github.com/munki/munki-pkg/tree/master/SuppressSetupAssistant

I won't add this functionality to pycreateuserpkg as it is not part of creating a user.
