### ISSUE TITLE
FileVault enabled user not appearing at loginwindow

### ISSUE THREAD

**Issue by ducksrfr** [gregneagle/pycreateuserpkg#12]
Users created with pycreateuserpkg do not appear at the FV loginwindow in macOS 10.13.3. The issue [might be related to secureToken](https://derflounder.wordpress.com/2018/01/20/secure-token-and-filevault-on-apple-file-system/#comment-33813)

-I create a new user with Setup Assistant
-A config profile is pushed from my MDM server to enforce FileVault
-I reboot, and am prompted to enable FV for SetupAssistant_user
-After logging in, I install foo.pkg created with pycreateuserpkg
-I enable foo_user for FV in System Preferences
-I run `sysadminctl interactive -secureTokenStatus foo_user` and receive a positive response that secureToken is enabled for foo_user
-I reboot, but only SetupAssistant_user appears at the FV loginwindow. If I log into SetupAssistant_user, and then visit the loginwindow, foo_user appears as expected.

**Comment by gregneagle** [comment]
This is a known issue. There is no resolution as there is no way to create a SecureToken when creating accounts non-interactively.

**Comment by gregneagle** [comment]
(The "resolution", such as it is, is to manually add a SecureToken using `sysadminctl` or possibly the Security prefs pane (FileVault sub-pane)) But a _package_ that creates a user will not be able to create a SecureToken.

**Comment by gregneagle** [comment]
To confuse matters even more: sometimes accounts created via pycreateuserpkg packages _do_ show up at the FV unlock screen.

We "bootstrap" our machines with a local admin account that is the 501 user. If I bootstrap a 10.13.3 machine, I can log into the machine with this local admin account and enable FileVault. I see a warning that "Some users are not able to unlock this disk", but clicking on this leads to an empty list. Re-locking and unlocking the Security prefs pane makes the warning go away.  I can then restart the machine, and the local admin account (which was, you remember, created via a pycreateuserpkg package) shows as the FV unlock window (It's the only account!) and I can successfully use it to unlock the disk and continue booting.

**Comment by ducksrfr** [comment]
how fun! lol

Thanks for your time, Greg. Most of my users are on Sierra, so I'm finally getting around to creating a High Sierra "image." This is still a really useful tool, I have a stash of loaner laptops that don't need the user to be FV-enabled. The --autologin option is great for that use.

**Comment by gregneagle** [comment]
It seems to me at least that Apple has rules about how accounts get Secure Tokens and FileVault enabled that we don’t yet understand and are not yet documented.
