### ISSUE TITLE
missing module named locallibs

### ISSUE THREAD

**Issue by Dragao75** [gregneagle/pycreateuserpkg#13]
Hi,

I use this script with success until recent. 

When I use the script (on a clean 10.13.3) I receive an error:
No module named locallibs
this error is even shown when retrieving the help (--help) 

I was trying to create a new admin account as my old(current) pkg is not working in 10.13.3 (pass is not accepted)

**Comment by gregneagle** [comment]
You didn’t copy/git clone the entire project.

**Comment by Dragao75** [comment]
Stupid me!
