### ISSUE TITLE
Using special characters in user passwords

### ISSUE THREAD

**Issue by flammable** [gregneagle/pycreateuserpkg#15]
Thanks for this!  Deploying our admin account with pycreateuserpkg and Munki has made the transition to macOS 10.13 much easier for us.

One issue I'm encountering: for some computers on campus, my department partners with another department to provide support to our users.  Although our local admin password is randomly generated, the other department requested a specific password for their local admin account.  This password contains both `$` and `!` characters.  I can't seem to create a working user pkg with these characters using pycreateuserpkg.

When escaping the characters, or quoting the entire password, the pkg is successfully created.  After deploying it to a Mac, though, the account will not accept the correct password.

I've warned the other department that they might need to change their password when we move to 10.13, so if this isn't possible, that's okay - I just wanted to make sure there isn't another way to accomplish this.  Is there something obvious I'm missing?

**Comment by gregneagle** [comment]
This is almost certainly a shell escaping issue as most shells use $ and ! as special characters. Have you tried interactively entering the password?

**Comment by flammable** [comment]
Cool, I didn't know it was possible to provide the password interactively.  That works great!  Thanks, Greg!

**Comment by gregneagle** [comment]
This is also arguably more secure than passing it as a parameter; it won't appear in your shell history.
