### ISSUE TITLE
Multiple instances overwrite one another

### ISSUE THREAD

**Issue by kolczk** [gregneagle/pycreateuserpkg#19]
Trying to create multiple admin accounts using this, but each time I install the new package it overwrites the previous user I had run.  UID's are all different.  Has anyone else expressed this and had a solution?  Thanks

**Comment by vmiller** [comment]
Are you giving each package a unique identifier?

**Comment by gregneagle** [comment]
Failure to give each package a unique package identifier would cause these symptoms as @vmiller implies.

**Comment by kolczk** [comment]
Thanks!  Knew it had to be something small I was missing.
