### ISSUE TITLE
Creating a user with a BLANK password?

### ISSUE THREAD

**Issue by bsom** [gregneagle/pycreateuserpkg#20]
Why can't I do this?  I haven't been able to find a way to get this to work.  It can be done from the macOS GUI but none of the command line options seem to work.

**Comment by gregneagle** [comment]
Why can't you do what?

**Comment by bsom** [comment]
Create a user with a BLANK password.  I thought the title said it all. :-)

**Comment by gregneagle** [comment]
Oh. Blank password. Don't know. Not important for me, so I'm not motivated to investigate. Dig in to the underlying commands and let us know what you find.

**Comment by bsom** [comment]
I've been digging for two days.  I was hoping someone had a recommendation because I can't seem to find anything.

**Comment by gregneagle** [comment]
Closing this as it was addressed in #26 and #27
