### ISSUE TITLE
Usage declaration incorrect

### ISSUE THREAD

**Issue by diwanicki** [gregneagle/pycreateuserpkg#22]
This may be a change in this branch only, as I’m interested in the Mojave compatibility changes, but the working order of invocation is different from what is specified in —help and in README.md. 

Should be:

Usage: createuserpkg /path/to/output.pkg [options]

Dumps to help output if you try to specify the options before the target.

**Comment by gregneagle** [comment]
No it "shouldn't".

You can specify the options before or after the output pkg path; it does not matter:

```
% ./createuserpkg --name foo --uid 1000 --version 1.0 --identifier com.foo foo.pkg
Password: 
Password (again): 
pkgbuild: Inferring bundle components from contents of /var/folders/tc/sd4_mtvj14jdy7cg21m2gmcw000495/T/tmp_RzL25/create_user
pkgbuild: Adding top-level postinstall script
pkgbuild: Wrote package to foo.pkg
```
and
```
 % ./createuserpkg foo.pkg --name foo --uid 1000 --version 1.0 --identifier com.foo 
Password: 
Password (again): 
pkgbuild: Inferring bundle components from contents of /var/folders/tc/sd4_mtvj14jdy7cg21m2gmcw000495/T/tmpBg0qkY/create_user
pkgbuild: Adding top-level postinstall script
pkgbuild: Wrote package to foo.pkg
```
Suspect whatever issue you are encountering is triggered by something other than option order.
