### ISSUE TITLE
System Policy: deny(1) file-write-create

### ISSUE THREAD

**Issue by BurgerCIN** [gregneagle/pycreateuserpkg#24]
Mojave errors when running the PKG for build 18A391

error	14:45:51.423343 -0400	kernel	Sandbox: shove(82456) System Policy: deny(1) file-write-create /private/var/db/dslocal/nodes/Default/users/xxx.plist

**Comment by gregneagle** [comment]
Please provide far more detail on how one might reproduce your issue.

**Comment by gregneagle** [comment]
(removed that additional info as not relevant)

**Comment by BurgerCIN** [comment]
I've been using this to deploy users to live systems, not disk images. That may be the difference.

sudo /Users/XXX/Desktop/pycreateuserpkg-master/createuserpkg -n testadmin -u 552 -p xxxx -f TESTAdmin -a -V 2 -i 4546 /Users/XXX/Desktop/TESTAdminNewPW.pkg

The pkg install fails with the error above in the console.

**Comment by gregneagle** [comment]
You are using the current code to create your pkgs, yes?
I've successfully installed pycreateuserpkg packages on Mojave as have others.
Packages built with older versions of this tool _will_ fail to install on Mojave.

**Comment by BurgerCIN** [comment]
That was it! Many thanks for your work!
