### ISSUE TITLE
Product Build

### ISSUE THREAD

**Issue by csteelatgburg** [gregneagle/pycreateuserpkg#28]
In order to include a package for installation using startosinstall it needs to be a product archive. What are you thoughts on this being added as an option to output a product archive with the needed product ID set?

**Comment by mistacabbage** [comment]
+1
Would help with Two Canoes Mac Deploy Stick.

**Comment by gregneagle** [comment]
`productbuild --package component_createuser.pkg product_archive_createuser.pkg` is pretty easy to do if you need a distribution-style/product archive package.

I don't have any plans to take the time to add a distribution-style output any time soon; it's not a bad idea, just incredibly low-priority for me.

**Comment by gregneagle** [comment]
Closing this old issue as "won't do"
