### ISSUE TITLE
Please Support macOS 10.15

### ISSUE THREAD

**Issue by kylejericson** [gregneagle/pycreateuserpkg#36]
Will you be working on getting this to work with 10.15?

**Comment by gregneagle** [comment]
Does it not?

**Comment by kylejericson** [comment]
I know that with 10.15 Python is be deprecated.

**Comment by gregneagle** [comment]
Yes, so you’ll need to install Python yourself.

**Comment by jelockwood** [comment]
There seems to be two possible sides to this issue.

1. Under Catalina using the pycreateuserpkg tool to create an Apple installer pkg
2. Running the resulting Apple installer pkg

The first operation would typically be done infrequently on an admin Mac and the simple solution for this is to if needed install a copy of Python.

The second is potentially more difficult. If as I believe is the case the resulting installer pkg still needs to run a python script then it is likely to fail as there will be no Python interpreter to execute it. @gregneagle correct me if I am wrong about this :)

I am under the impression that Apple are encouraging developers who want to use a scripting language like Python to embed a runtime in the app - much like an increasing number of developers now include an embedded Java JRE in their apps.

This would require in this case Greg to do that if he so chose.

See these articles as possible guides - 
https://medium.com/python-pandemonium/embedding-a-python-application-in-macos-d866adfcaf94
http://joaoventura.net/blog/2016/embeddable-python-osx/

This tool looks relevant - https://pypi.org/project/py2app/

**Comment by gregneagle** [comment]
I will not be including a Python interpreter with pycreateuserpkg.

Also relevant: https://github.com/gregneagle/relocatable-python

**Comment by kylejericson** [comment]
Thanks I love this script so I would hate for it to die with 10.15.

**Comment by gregneagle** [comment]
It won't die -- it will just have a new prerequisite if/when Apple removes Python. But Python 2.7.x is still available in all the Catalina betas so far.

**Comment by jelockwood** [comment]
@gregneagle @kylejericson 
Yeah. My understanding is that the current quite old version of Python will still be in Catalina but not in the one after Catalina. So the issue will arise but not yet.
