### ISSUE TITLE
Unable to create user

### ISSUE THREAD

**Issue by sfeldersiprep** [gregneagle/pycreateuserpkg#37]
I am trying to create a local admin user but with no success. In looking at the pkg contents and the payload, it seems that there are no directories past 'private' - I was expecting /private/var/db/dslocal/nodes/Default/users/localadmin.plist. It does look like that plist is created but is in the scripts directory.

I've followed the sample at the bottom of the ReadMe as well as a tutorial at https://derflounder.wordpress.com/2017/12/24/creating-local-user-accounts-with-pycreateuserpkg/. I've also tried on both T2 machine and older machine, both running Mojave.

Actual commands: 
`./createuserpkg -n localadmin -u 506 -a -i org.siprep.localadmin.pkg -V 1.0 localadmin.pkg`
`./createuserpkg --name="localadmin" --uid=504 --fullname="LocalAdministrator" --shell="/bin/bash" --admin --version=1.0 --identifier="org.siprep.admin_user_setup" "Create_Local_aDmIn_user_account.pkg"`

What am I missing?

**Comment by gregneagle** [comment]
Have you looked in /var/log/install.log for clues as to why it might be failing for you? Works here and for  others.

**Comment by gregneagle** [comment]
```
$ ./createuserpkg -n localadmin -u 506 -a -i org.siprep.localadmin.pkg -V 1.0 localadmin.pkg
Password: 
Password (again): 
pkgbuild: Inferring bundle components from contents of /var/folders/tc/sd4_mtvj14jdy7cg21m2gmcw000495/T/tmpOdqZD9/create_user
pkgbuild: Adding top-level postinstall script
pkgbuild: Wrote package to localadmin.pkg
$ id 506
id: 506: no such user
$ sudo installer -pkg localadmin.pkg -target /
installer: Package name is localadmin
installer: Installing at base path /
installer: The install was successful.
$ id 506
uid=506(localadmin) gid=20(staff) groups=20(staff),12(everyone),61(localaccounts),80(admin),703(com.apple.sharepoint.group.2),701(com.apple.sharepoint.group.1),33(_appstore),98(_lpadmin),100(_lpoperator),204(_developer),250(_analyticsusers),395(com.apple.access_ftp),704(com.apple.sharepoint.group.3)
$ dseditgroup -o checkmember -m localadmin admin
yes localadmin is a member of admin
```

**Comment by gregneagle** [comment]
<img width="668" alt="Screen Shot 2019-07-19 at 2 58 21 PM" src="https://user-images.githubusercontent.com/700560/61567859-e0062b00-aa35-11e9-8580-7f5745cc71d9.png">

**Comment by sfeldersiprep** [comment]
Thanks for the reply. Yes, forgot to mention that I've checked the logs and see nothing that stands out, either by keyword or time frame. I also get no error thrown at run.

```
Faculty6778:pycreateuserpkg-master sfelder$ ./createuserpkg -n localadmin -u 506 -a -i org.siprep.localadmin.pkg -V 1.0 localadmin.pkg
Password: 
Password (again): 
pkgbuild: Inferring bundle components from contents of /var/folders/0b/gfvn1l210vzf7f6rg5r6f24m0000gp/T/tmpmaHra6/create_user
pkgbuild: Adding top-level postinstall script
pkgbuild: Wrote package to localadmin.pkg
```
Thanks for the other items, showing that it works. Am I correct that I should be seeing that whole directory path within the payload directory - /private/var/db/dslocal/nodes/Default/users/localadmin.plist? I see nothing after private. 

Are pycreateuserpkg events logged anywhere else that I can check?

**Comment by gregneagle** [comment]
No you should not see any payload at all. The account is created via postinstall script in the package.
All logging is done by Apple's installer, and would appear in /var/log/install.log.

pycreateuserpkg is a tool that creates a _package_. You use Apple's installer to install the package, and Apple's installer would log its actions (and errors).

One debugging technique is to expand the flat package:

`pkgutil --expand localadmin.pkg expanded_pkg`

Then run the postinstall script manually:

`./expanded_pkg/scripts/postinstall / / / /`

**Comment by sfeldersiprep** [comment]
OK, thanks. I'll keep banging on it.

**Comment by gregneagle** [comment]
Closing this old issue since there are no updates.
