### ISSUE TITLE
Shell option error?

### ISSUE THREAD

**Issue by jelockwood** [gregneagle/pycreateuserpkg#47]
Based on seeing this comment - https://github.com/gregneagle/pycreateuserpkg/issues/39#issuecomment-522852426 I added the following to my command

-shell zsh

This however caused it to complain I was using two file names. When I tried --shell=zsh _in the same position_ it worked fine.

Does this indicate a parsing error in your script?

**Comment by gregneagle** [comment]
Big difference in command parsing between "-shell" and "--shell"

"-shell" is parsed the same as "-s hell"

So I'd say it's more likely an error on your end.

**Comment by jelockwood** [comment]
Mea Culpa.
