### ISSUE TITLE
Using pycreateuserpkg with AutoDMG

### ISSUE THREAD

**Issue by jelockwood** [gregneagle/pycreateuserpkg#48]
I have in the past successfully used an installer package created using the pycreateuserpkg script with AutoDMG. In fact it (and its predecessors) has been one of the few installer packages to historically have been trouble free with AutoDMG.

I am currently experimenting with creating a Catalina image using AutoDMG and a bog standard image does work - that is one with zero installers. I have tried adding an installer generated using the latest pycreateuserpkg and this seems to fail as when I boot from the end resulting Catalina installed via the AutoDMG image it still goes in to the Apple setup wizard indicating it has not successfully run.

I am under the impressions that signing of installers for Catalina might now been a very critical issue and was wondering if there is any advice on what one needs to do to successfully get to run as part of an AutoDMG image?

I am using the beta of AutoDMG to get Catalina support, my source Catalina is in an image generated using Greg's installinstallmacos script. (AutoDMG needs it to be in a disk image.) As mentioned I am using the latest pycreateuserpkg and I just double checked and refreshed my copy and built another new installer pkg.

**Comment by gregneagle** [comment]
Not sure why you think creating a user via a package will stop Apple's Setup Assistant from running.
It's not clear at all from your description if the user account is properly created.
In my testing, the current pycreateuserpkg code works fine to create users on Catalina.

**Comment by gregneagle** [comment]
(reading your issue again:) I no longer use AutoDMG and have no idea if AutoDMG has additional hurdles to jump. I doubt I'll have the time to test (and have no internal motivation to do it). If someone identifies a specific issue with pycreateuserpkg + AutoDMG + Catalina and has a fix, I'd be happy to look at that.

**Comment by jelockwood** [comment]
I have subsequently confirmed your pkg does run and successfully create the user. However it does not create the file which marks it as having previously run Apple Setup Assistant so that was still launching after booting.

I had perhaps mistakenly thought your pkg also disabled the setup assistant. I am closing this issue.

**Comment by gregneagle** [comment]
I have always used a purpose-specific package to install the correct file(s) to disable the setup assistant. Many examples available on the web, and here's one for use with munkpkg: https://github.com/munki/munki-pkg/tree/master/SuppressSetupAssistant

Consider that some orgs might want to create a consistent local admin account before deployment, but still want the Setup Assistant to run to allow the actual user to create their own local user account.
