### ISSUE TITLE
Feature: add tokenidentity to authentication_authority

### ISSUE THREAD

**Issue by GregoryEAllen** [gregneagle/pycreateuserpkg#50]
I propose `-t` or `--token <HASH>`, where the hash matches that returned by `sc_auth`.

If this sounds reasonable, I'm working on a PR.

I'd move `authentication_authority` out of `userlist.py` and handle it more like the other keys.

**Comment by gregneagle** [comment]
I have no idea what problem you are attempting to solve.

**Comment by GregoryEAllen** [comment]
I have to have smart card authentication. In particular, we're using YubiKeys. I'm trying to add the hash of the administrator's smart card to the `AuthenticationAuthority`. A paired smart card looks like:

```
syrinx:~ gallen$ dscl . read /Users/gallen AuthenticationAuthority
AuthenticationAuthority:
 ;ShadowHash;HASHLIST:<SALTED-SHA512-PBKDF2>
 ;SecureToken;
 ;tokenidentity;96AD5967A5D7A6D5A765D9A6D965AD967A5D9765
```

**Comment by GregoryEAllen** [comment]
I have changes that add to `AuthenticationAuthority` and seem to look right. I went to test on my Catalina box, but it can't create a working account. The account is missing basic keys like `RealName` and `UniqueID`.

It seems OK on High Sierra, but big stuff seems broken on Catalina.

**Comment by gregneagle** [comment]
Obviously I can't accept/merge changes that break currently-working functionality. I'm assuming you are making your changes to the Objective-C createuser tool -- create_user.py has been abandoned since it does not work any longer on Catalina.

**Comment by gregneagle** [comment]
(https://github.com/gregneagle/pycreateuserpkg#new-13-aug-2019)

Actually, now I'm not sure that create_user.py is no longer functional in Catalina, but I am sure it has been abandoned.

**Comment by GregoryEAllen** [comment]
My issue on Catalina was that there was already a user with the specified `uid`. The installer said that the package installed successfully, but there was a conflict.

Edit: now working, no change to `createuser` needed.
