### ISSUE TITLE
Apply pwpolicy right away

### ISSUE THREAD

**Issue by vasquesbc** [gregneagle/pycreateuserpkg#54]
How about an option to supply a pwpolicy.plist within the package?
And: is it technically possible to create a User by pycreateuserpkg that has to set it's password at first Login?

**Comment by jelockwood** [comment]
I will leave it for Greg to comment on whether it will be possible to supply a pwpolicy.

However the pwpolicy command also supports requiring the password to be changed on login. I don't believe it will be possible to set no password at all initially. I believe Mojave introduced an OS level requirement of a minimum password length of 4 characters whereas before that a length of zero characters i.e. no password at all was possible.

I use a simple default password and then used pwpolicy to require a the user change it.

Oops! Just remember Catalina has broken this featue. If you use it the account becomes unusable. It can be 'repaired' by using the System Preferences -> Users & Groups option to reset the user password. Another example of Apple making life difficult for administrators. :(

**Comment by gregneagle** [comment]
I don’t have the need for either of these features so it’s not something I plan to spend any time on. Sorry!

**Comment by vasquesbc** [comment]
@gregneagle Thats ok since it's your project and i'am grateful for its existence.

@jelockwood i've read about the fact that it's broken, however, i did not experience that issue with 10.5.5.
But forcing the user to change it's password at first login doesn't work. It seams the user had to be logged in once and afterwards the policy has to be set to show effect. That's dissatisfying :(
