### ISSUE TITLE
Apple Silicon Support

### ISSUE THREAD

**Issue by mpermann** [gregneagle/pycreateuserpkg#60]
I attempted to install a pkg I created on my Intel MacBook Pro with Big Sur installed on an Apple Silicon M1 Mac and it didn't work properly. The error in the install.log file indicated there was an issue running the post install script. With my limited understanding of coding, I guessed that the issue most likely was caused by the createuser binary in the pkg_scripts folder. I opened the createuser.xcodeproj in the latest version of Xcode and attempted to build new version of the binary that supported the Apple Silicon architecture. I was able to successfully build a new binary and substituted it with the original and created a new pkg installer. The new installer did install properly on an Apple Silicon Mac and a new user account was added. I'm wondering if you would be able to make those changes to the project so that it will work on Apple Silicon Macs?

**Comment by gregneagle** [comment]
Thanks for reminding me about this. I've done the same as you internally (built the createuser tool as universal) but haven't done it for the public GitHub project.

**Comment by gregneagle** [comment]
Here: https://github.com/gregneagle/pycreateuserpkg/commit/dcc9ee6d140048aa74fa33f880a4f3c3cb8ada17
