### ISSUE TITLE
getting this error when running about syntax error on line 63

### ISSUE THREAD

**Issue by jnubz** [gregneagle/pycreateuserpkg#65]
./createuserpkg.py: line 63: syntax error near unexpected token `('
./createuserpkg.py: line 63: `        '--generateduid', '-G', help='GeneratedUID (UUID). Optional.')'

**Comment by gregneagle** [comment]
See https://github.com/gregneagle/pycreateuserpkg#new-13-march-2022

You now need to specify the python interpreter you wish to use.

**Comment by jnubz** [comment]
Thank you, Greg. It worked once i used `munki-python` and typed it all out manually. For some reason copying and pasting my arguments threw even more errors when using `munki-python`.
