### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by damienf55** [gregneagle/pycreateuserpkg#68]
Hi

there is a syntax error in last version :

`./createuserpkg.py: line 63: syntax error near unexpected token `('
./createuserpkg.py: line 63: `        '--generateduid', '-G', help='GeneratedUID (UUID). Optional.')'`

Thanks

**Comment by gregneagle** [comment]
I'm not seeing that in either my local git repo or here:
https://github.com/gregneagle/pycreateuserpkg/blob/main/createuserpkg.py#L62-L66
