### ISSUE TITLE
Feature Request: Specify UUID

### ISSUE THREAD

**Issue by vasquesbc** [gregneagle/pycreateuserpkg#7]
Setting the same UUID on several machines for a specific user is important for SAN-Environments where ACL Permissions are used

**Comment by gregneagle** [comment]
Unless I misunderstand what you are talking about, that feature is already present, using Appke’s name for it: GeneratedUID.

**Comment by vasquesbc** [comment]
I'm so sorry - totally missed that option while testing.

**Comment by jelockwood** [comment]
@vasquesbc 
For creating a user to ensure the same UID (or generated UID) is used on multiple machines you should not use the pycreateuserpkg tool - although it would work, instead you should be using mobile accounts where a local account is created and linked to the matching user account in a directory server e.g. Open Directory or Active Directory. These store all the data locally, store the user account locally, will use the exact same UID as that defined in the directory server thereby ensuring ACLs work properly and will sync passwords to the directory server for off and online access. 

I use pycreateuserpkg or similar for creating local only account(s) which might be used for administration.

However if you have no directory service then the pycreateuserpkg would be a workaround.
