### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by timsutton-sl** [gregneagle/pycreateuserpkg#8]
I'm hoping to somehow include parts of this repo in https://github.com/timsutton/osx-vm-templates/pull/82#issuecomment-342733374.. is there a license under which you would like to make the code (more specifically, those which are yours) available for re-use?

**Comment by gregneagle** [comment]
See if recent pushes address your question. If so, feel free to close.

**Comment by timsutton-sl** [comment]
Indeed they do. Thank you!
