### ISSUE TITLE
command not creating a .pkg

### ISSUE THREAD

**Issue by KodySalak** [gregneagle/pycreateuserpkg#9]
This command I am running under is creating a file, but not a .pkg. Isn't that what it's supposed to do? 

Command: /Users/test/Desktop/pycreateuserpkg-master/createuserpkg --name=Administrator --uid=499 --version=0.1 --identifier=com.XXXX.createuseradmin --password=###### --admin /Users/Shared/Admin

**Comment by gregneagle** [comment]
A package is a file. You’ve just named it in a way that the Finder doesn’t recognize it is a package. Add “.pkg” to the end of the filename and the Finder will be happier.
